version: '3.4'

services:
  nextjsfullstackauth:
    image: nextjsfullstackauth
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
